// Canonical action codes for audit logs. Keep these stable — downstream
// alerting / SIEM rules will key on them.
export const AUDIT_ACTIONS = {
  // Auth
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",

  // Users
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",

  // Workspaces
  WORKSPACE_CREATED: "WORKSPACE_CREATED",
  WORKSPACE_UPDATED: "WORKSPACE_UPDATED",
  WORKSPACE_DELETED: "WORKSPACE_DELETED",

  // Posts
  POST_CREATED: "POST_CREATED",
  POST_UPDATED: "POST_UPDATED",
  POST_DELETED: "POST_DELETED",
  POST_PUBLISHED: "POST_PUBLISHED",

  // AI jobs
  AI_CONTENT_JOB_QUEUED: "AI_CONTENT_JOB_QUEUED",
  AI_HASHTAG_JOB_QUEUED: "AI_HASHTAG_JOB_QUEUED",
  AI_IMAGE_JOB_QUEUED: "AI_IMAGE_JOB_QUEUED",

  // Social integrations
  // Use generic actions with `metadata.platform` instead of one per-platform
  // constant so adding new platforms is a data-only change.
  INTEGRATION_CONNECTED: "INTEGRATION_CONNECTED",
  INTEGRATION_DISCONNECTED: "INTEGRATION_DISCONNECTED",
  INTEGRATION_OAUTH_INITIATED: "INTEGRATION_OAUTH_INITIATED",
  POST_PLATFORM_PUBLISH_QUEUED: "POST_PLATFORM_PUBLISH_QUEUED",
  POST_PLATFORM_PUBLISH_SUCCEEDED: "POST_PLATFORM_PUBLISH_SUCCEEDED",
  POST_PLATFORM_PUBLISH_FAILED: "POST_PLATFORM_PUBLISH_FAILED"
} as const;

export type AuditAction =
  (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
